language: php
sudo: false

matrix:
  include:
    - php: "7.2"
    - php: "7.3"
    
before_script:
  - composer update
  # for the FileHelper tests, specific ini settings are required
  - phpenv config-add tests/tests.php.ini
